learning_rate_monitor:
  # _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: ${train.interval}

timer:
  # _target_: callbacks.timer.Timer
  step: True
  inter_step: False
  epoch: True
  val: True

score:
  # _target_: callbacks.score.Score
  enable: True

params:
  # _target_: callbacks.params.ParamsLog
  total: True
  trainable: True
  fixed: True

memory_monitor:
  enable: True

experiment_logger:
  enable: False
  output_file: /work/temp/logs/experiment.csv

memory_profiler:
  enable_callback: false  
  start_step: 5
  profile_steps: 20
  record_shapes: false
  profile_memory: false
  with_stack: false
  output_dir: null

weight_change_visualizer:
  enable: false

flops_counter:
  enable: false
